### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by Rayman** [blackcoffeerobotics/vector_pursuit_controller#4]
Hi, thank you for this package! I was analysing your code and I have a question:

`phi_1` and `phi_2` I can relate to equation `3.49`. But where can I find the definition of `term_1` and `term_2`? I'm trying to understand where they come from. 

Thank you for your answer!

**Comment by exMachina316** [comment]
Hey @Rayman!! Since we are doing the calculations in the robot frame, we use a modified version of `3.55`, here each multiplicative term on the right side of `-` are term1 and term2 resp.

![Screenshot from 2024-10-20 19-22-03](https://github.com/user-attachments/assets/1feb268c-c5d7-4384-aa3f-fb1af7e90ad6)
